name: flutter_centralized_exception_handler_example
description: Centralized exception handler example

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP Client
  dio: ^5.2.0+1
  pretty_dio_logger: ^1.3.1
  curl_logger_dio_interceptor: ^1.0.0
  dio_smart_retry: ^5.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lint
  flutter_lints: ^2.0.1
  analyzer: ^5.13.0

  # Data
  build_runner: ^2.4.4
  json_serializable: ^6.7.0
  copy_with_extension_gen: ^5.0.2

  # Tests
  mockito: ^5.4.1
  covadge: ^0.0.1


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/json/
